version: '3'

services:
  database:
    image: postgres:16.1-alpine
    restart: always
    expose:
      - 5432
    env_file:
      - .env
    networks:
      - backend
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database
    restart: on-failure
    networks:
      - backend

networks:
  backend: