version: '3'

services:
  proxy:
    image: nginx
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=3000
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
    depends_on:
      - server
    networks:
      - backend
  database:
    image: postgres:16.1-alpine
    restart: always
    expose:
      - 5432
    env_file:
      - ./.env
    networks:
      - backend
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    env_file:
      - ./.env
    depends_on:
      - database
    restart: on-failure
    networks:
      - backend

networks:
  backend: